name: maven-example
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branchCondition: all
- name: build
  steps:
  - runScriptConfig:
      image: maven
      isShell: true
      shellScript: |-
        mvn dependency:go-offline
        mvn integration-test
- name: publish
  steps:
  - buildImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: project/maven-example:${CICD_EXECUTION_SEQUENCE}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
